spermbank(GAPデプロイ前)/spermbankproject/donors/urls.py
from django.urls import path,include
from . import views
from .views import DonorListView ,DonorCreateView,DonorSearchedView


app_name='donors'

urlpatterns = [
    path('',DonorListView.as_view(),name='donors.list'),
    path('donor_create/',views.DonorCreateView.as_view(),name='create'),
    path('donor_search/',views.SearchFormView.as_view(),name='search'),
    path('donor_search/donor_searched/',views.DonorSearchedView.as_view(),name='searched'),
    ]

spermbank(GAPデプロイ前)/spermbankproject/spermbankproject/urls.py
from django.contrib import admin
from django.urls import path,include

from django.views.generic import TemplateView


app_name='donors'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='top.html'),name='top'),
    path('donor/',include('donors.urls')),
]

spermbank(GAPデプロイ前)/spermbankproject/donors/models.py
from django.db import models

HAIR=(("0","ダークブラウン"),("1","ダークブロンド"),("2","ブラウン"),("3","ブロンド"),("4","黒色"),("5","赤色"),("6","白色"))
HEIGHT = (("0","-159"),("1","160-169"),("2","170-179"),("3","180-189"),("4","190-"))
WEIGHT = (("0","-50"),("1","50-59"),("2","60-69"),("3","70-79"),("4","80-89"),("5","90-"))
ICI_IUI = (("0","ICI-未洗浄"),("1","IUI-洗浄済"))
BLOOD=(("0","A-"),("1","A+"),("2","AB-"),("3","AB+"),("4","B-"),("5","B+"),("6","O-"),("7","O+"))
TODAY_PHOTO = (("0","いいえ"),("1","はい"))
PROFILE = (("0","ドナー独占権"),("1","基本"),("2","詳細"))
EYE_COLOR = (("0","灰色"),("1","青色"),("2","青色/灰色"),("3","青色/緑色"),("4","茶色"),("5","茶色/灰色"),("6","茶色/緑色"),("7","緑色"),("8","緑色/灰色"))
MOT = (("0","MOT5"),("1","MOT10"),("2","MOT20"),("3","MOT30"),("4","MOT40"),("5","MOT50+"))

class Donor(models.Model):
    number = models.CharField(max_length=20,verbose_name="ID",null=True)
    hair_color = models.CharField(max_length=20,verbose_name="髪の色", choices=HAIR,null=True)
    height = models.CharField(max_length=20,verbose_name="身長(cm)", choices=HEIGHT,null=True)
    weight = models.CharField(max_length=20,verbose_name="体重(kg)", choices=WEIGHT,null=True)
    ICI_IUI = models.CharField(max_length=20,verbose_name="ICI/IUI", choices=ICI_IUI,null=True)
    blood_type = models.CharField(max_length=20,verbose_name="血液型", choices=BLOOD,null=True)
    today_photo = models.CharField(max_length=20,verbose_name="現在の写真", choices=TODAY_PHOTO,null=True)
    profile = models.CharField(max_length=20,verbose_name="プロフィール", choices=PROFILE,null=True)
    eye_color = models.CharField(max_length=20,verbose_name="瞳の色", choices=EYE_COLOR,null=True)
    mot = models.CharField(max_length=20,verbose_name="運動能力", choices=MOT,null=True)
    memo = models.TextField(max_length=200)

class DonorSearch(models.Model):
    color_filter = models.CharField(max_length=20,verbose_name="髪の色", choices=HAIR,null=True)

spermbank(GAPデプロイ前)/spermbankproject/donors/forms.py
from django import forms
from .models import Donor,DonorSearch
from .models import HAIR
from .models import HEIGHT

class DonorForms(forms.ModelForm):
    class Meta:
        model = Donor
        fields = ('number','hair_color','height','weight','ICI_IUI','blood_type','today_photo','profile','eye_color','mot','memo')


class DonorSreachForm(forms.ModelForm):
    class Meta:
        model = Donor
        # fields = ('number','hair_color','height','weight','ICI_IUI','blood_type','today_photo','profile','eye_color','mot')
        fields =('hair_color',)

spermbank(GAPデプロイ前)/spermbankproject/donors/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,CreateView
from django.views import generic
from .models import Donor,DonorSearch
from .forms import DonorForms,DonorSreachForm

from django.db.models import Q
import logging

from django.template import RequestContext
from django.shortcuts import render_to_response
 # Create your views here.

logger = logging.getLogger('development')

class DonorListView(ListView):
    template_name = 'donors/donors_list.html'
    model = Donor

class DonorCreateView(CreateView):
    template_name = 'donors/donors_create.html'
    model = Donor
    form_class = DonorForms
    success_url = '/donor/'

class SearchFormView(CreateView):
    template_name = 'donors/donors_search.html'
    model = DonorSearch
    form_class = DonorSreachForm
    success_url = '/donor/'
    
class DonorSearchedView(ListView):
    template_name = 'donors/donors_searched_list.html'
    model = Donor
    

   
    def get_context_data(self,**kwargs):
        context = super(DonorSearchedView,self).get_context_data(**kwargs)
        donors = self.model.objects.all()
        context['donors'] = donors

        default_data = {
        'number':6,
        'hair_color':2,
        'height':1,
        'weight':0,
        'ICI_IUI':0,
        'blood_type':6,
        'today_photo':1,
        'profile':1,
        'eye_color':2,
        'mot':3,
        }
        test_form = DonorSreachForm(initial=default_data)
        context['test_form']=test_form

        return context
 

    def get_queryset(self):
        object_list = self.model.objects.all()
        q_color = self.request.GET.get('color')
        q_height = self.request.GET.get('height')
        q_weight = self.request.GET.get('weight')
        q_ICI_IUI = self.request.GET.get('IUI_ICI')
        q_blood_type = self.request.GET.get('blood_type')
        q_today_photo = self.request.GET.get('today_photo')
        q_profile = self.request.GET.get('profile')
        q_eye_color = self.request.GET.get('eye_color')
        q_mot = self.request.GET.get('mot')       

        
        # object_list = object_list.filter(hair_color = q_color)
        # object_list = object_list.filter(height = q_height)
        # object_list = object_list.filter(weight = q_weight)
        # object_list = object_list.filter(ICI_IUI = q_ICI_IUI)
        # object_list = object_list.filter(blood_type = q_blood_type)
        # object_list = object_list.filter(today_photo = q_today_photo)
        # object_list = object_list.filter(profile = q_profile)
        # object_list = object_list.filter(eye_color = q_eye_color)
        # object_list = object_list.filter(mot = q_mot)
        object_list = object_list.filter(Q(mot = q_mot)|Q(hair_color = q_color))
        

                

        return object_list
        

spermbank(GAPデプロイ前)/spermbankproject/templates/donors/donors_create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<body>    
    <h1>ドナー作成画面</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="create_button" type="submit" value="保存">
    </form>
</body>
{% endblock %}

spermbank(GAPデプロイ前)/spermbankproject/templates/donors/donors_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<body>
    <h1>ドナーリスト</h1>
    <p class="create_button"><a href="/donor/donor_create/">ドナー新規登録</a></p>
    <p class="create_button"><a href="/donor/donor_search/donor_searched">ドナー検索</a></p>
{% for donor in object_list %}
<div class="donors_list">
    <p>ID:{{ donor.number }}</p>
    <p>髪の色：{{ donor.get_hair_color_display }}</p>
    <p>身長：{{ donor.get_height_display }}</p>
    <p>体重：{{ donor.get_weight_display }}</p>
    <p>ICI/IUI：{{ donor.get_ICI_IUI_display }}</p>
    <p>血液型：{{ donor.get_blood_type_display }}</p>
    <p>現在の写真：{{ donor.get_today_photo_display }}</p>
    <p>プロフィール：{{ donor.get_profile_display }}</p>
    <p>瞳の色：{{ donor.get_eye_color_display }}</p>
    <p>運動能力：{{ donor.get_mot_display }}</p>
    <p>メモ：{{ donor.memo }}</p>
</div>
{% endfor %}


</body>
{% endblock %}

spermbank(GAPデプロイ前)/spermbankproject/templates/donors/donors_search.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- <body>    
    <h1>ドナー検索画面</h1>
    <form action="" method="get">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="create_button" type="submit" value="検索">
    </form>
    <a href="donor_searched/">検索結果</a>
</body> -->

<body>    
    <h1>ドナー検索画面</h1>
    <form action="" method="get">
        <label>髪の色：<input type="text" size="20" name="color"></label>
        <input class="create_button" type="submit" value="検索">
    </form>
    <a href="donor_searched/">検索結果</a>
    {% if color %}
        {{ color }}さん、こんにちは。
    {% endif %}
</body>
{% endblock %}

spermbank(GAPデプロイ前)/spermbankproject/templates/donors/donors_searched_list.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}

{% block content %}
<body>
    <h1>ドナー検索リスト</h1>
    <p>検索条件にヒットするドナーが表示されます</p>

    {% for donor in object_list %}
    <div class="donors_list">
        <p>ID:{{ donor.number }}</p>
        <p>髪の色：{{ donor.get_hair_color_display }}</p>
        <p>身長：{{ donor.get_height_display }}</p>
        <p>体重：{{ donor.get_weight_display }}</p>
        <p>ICI/IUI：{{ donor.get_ICI_IUI_display }}</p>
        <p>血液型：{{ donor.get_blood_type_display }}</p>
        <p>現在の写真：{{ donor.get_today_photo_display }}</p>
        <p>プロフィール：{{ donor.get_profile_display }}</p>
        <p>瞳の色：{{ donor.get_eye_color_display }}</p>
        <p>運動能力：{{ donor.get_mot_display }}</p>
        <p>メモ：{{ donor.memo }}</p>
    </div>
    {% endfor %}
    <h1>ドナー検索</h1>
    <form action="" method="get" name="filter_form">
        <br><p>髪の色：</p>
        <input type="radio" id="filter_color" name="color" value=0>ダークブラウン
        <input type="radio" id="filter_color" name="color" value=1>ダークブロンド
        <input type="radio" id="filter_color" name="color" value=2>ブラウン
        <input type="radio" id="filter_color" name="color" value=3>ブロンド
        <input type="radio" id="filter_color" name="color" value=4>黒色
        <input type="radio" id="filter_color" name="color" value=5>赤色
        <input type="radio" id="filter_color" name="color" value=6>白色
        <br>
        <!-- <br><p>身長：</p>
        <input type="radio" id="filter_height" name="height" value=0>-159
        <input type="radio" id="filter_height" name="height" value=1>160-169
        <input type="radio" id="filter_height" name="height" value=2>170-179
        <input type="radio" id="filter_height" name="height" value=3>180-189
        <input type="radio" id="filter_height" name="height" value=4>190-
        <br>
        <br><p>体重：</p>
        <input type="radio" id="filter_weight" name="weight" value=0>-50
        <input type="radio" id="filter_weight" name="weight" value=1>50-59
        <input type="radio" id="filter_weight" name="weight" value=2>60-69
        <input type="radio" id="filter_weight" name="weight" value=3>70-79
        <input type="radio" id="filter_weight" name="weight" value=4>80-89
        <input type="radio" id="filter_weight" name="weight" value=5>90-
        <br>
        <br><p>ICI/IUI：</p>
        <input type="radio" id="filter_ICI_IUI" name="ICI_IUI" value=0>未洗浄
        <input type="radio" id="filter_ICI_IUI" name="ICI_IUI" value=1>洗浄済み
        <br>
        <br><p>血液型：</p>
        <input type="radio" id="filter_blood_type" name="blood_type" value=0>A-
        <input type="radio" id="filter_blood_type" name="blood_type" value=1>A+
        <input type="radio" id="filter_blood_type" name="blood_type" value=2>AB+
        <input type="radio" id="filter_blood_type" name="blood_type" value=3>AB-
        <input type="radio" id="filter_blood_type" name="blood_type" value=4>B-
        <input type="radio" id="filter_blood_type" name="blood_type" value=5>B+
        <input type="radio" id="filter_blood_type" name="blood_type" value=6>O-
        <input type="radio" id="filter_blood_type" name="blood_type" value=7>O+
        <br>
        <br><p>現在の写真：</p>
        <input type="radio" id="filter_today_photo" name="today_photo" value=0>はい
        <input type="radio" id="filter_today_photo" name="today_photo" value=1>いいえ
        <br>
        <br><p>プロフィール：</p>
        <input type="radio" id="filter_profile" name="profile" value=0>ドナー独占権
        <input type="radio" id="filter_profile" name="profile" value=1>基本
        <input type="radio" id="filter_profile" name="profile" value=2>詳細
        <br>
        <br><p>瞳の色：</p>
        <input type="radio" id="filter_eye_color" name="eye_color" value=0>灰色
        <input type="radio" id="filter_eye_color" name="eye_color" value=1>青色
        <input type="radio" id="filter_eye_color" name="eye_color" value=2>青色/灰色
        <input type="radio" id="filter_eye_color" name="eye_color" value=3>青色/緑色
        <input type="radio" id="filter_eye_color" name="eye_color" value=4>茶色
        <input type="radio" id="filter_eye_color" name="eye_color" value=5>茶色/灰色
        <input type="radio" id="filter_eye_color" name="eye_color" value=6>茶色/緑色
        <input type="radio" id="filter_eye_color" name="eye_color" value=7>緑色
        <input type="radio" id="filter_eye_color" name="eye_color" value=8>緑色/灰色
        <br> -->
        <br><p>運動能力：</p>
        <input type="radio" id="filter_mot" name="mot" value=0>MOT5
        <input type="radio" id="filter_mot" name="mot" value=1>MOT10
        <input type="radio" id="filter_mot" name="mot" value=2>MOT20
        <input type="radio" id="filter_mot" name="mot" value=3>MOT30
        <input type="radio" id="filter_mot" name="mot" value=4>MOT40
        <input type="radio" id="filter_mot" name="mot" value=5>MOT50+
        <br>
        
        <button class="create_button" id="filter">絞り込み</button>
    </form>

    


</body>
{% endblock %}